---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: true
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: update repository index
    dnf:
      update_cache: true
    when: ansible_distribution in ['CentOS', 'Rocky']

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == 'Rocky'

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == 'Rocky'
