---
# sudo docker run --detach --publish 27017:27017 \
# --env MONGO_INITDB_ROOT_USERNAME=admin \
# --env MONGO_INITDB_ROOT_PASSWORD=password \
# --name mongodb --net mongo-network mongo


# sudo docker run --detach --publish 8081:8081 \
# --env ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
# --env ME_CONFIG_MONGODB_ADMINPASSWORD=password \
# --net mongo-network --name mongo-express \
# --env ME_CONFIG_MONGODB_SERVER=mongodb \
# mongo-express

version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: unless-stopped  # needed to stop this from stopping
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

# Docker Compose takes care of creating a common Network!
