---

- hosts: all
  become: true
  tasks:

  - name: remove apache and php packages for DEB servers
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache and php packages for RPM servers
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution in ["centos", "Rocky"]
