---

- hosts: all
  become: true
  pre_tasks:  # run before anything else

    - name: install updates (RPM)
      tags: always
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "Rocky"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution in ["Ubuntu", "Debian"]


- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php packages for DEB servers
      tags: apache, apache2, ubuntu
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php packages for RPM servers
      tags: apache, apache2, httpd
      package:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution in ["centos", "Rocky"]

    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (RPM)
      tags: rocky, db, mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Rocky"

    - name: install mariadb package (DEB)
      tags: rocky, db, ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
